---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactbackendappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: contactbackend
 template:
  metadata:
   name: contactbackend
   labels:
     app: contactbackend
  spec:
    containers:
    - name: contactbackendcontainer
      image: contact_backend_app
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: contactbackendsvc
spec:
  type: NodePort
  selector:
   app: contactbackend
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30001
...
